trigger:
  tags:
    include:
      - "v*"

resources:
  containers:
    - container: node18
      image: node:18-buster

pool:
  docker

variables:
- group: pipeline

jobs:
- job: GitHubSync
  container: node18
  steps:
  - checkout: self

  - script: |
      TAG_NAME=$(Build.SourceBranchName)
      if [[ "$TAG_NAME" == v2* ]]; then
        echo "Tag starts with v2. Sync starting..."
        BRANCH_NAME=$(echo $TAG_NAME | sed 's/^refs\/tags\///' | sed 's/\./_/g')

        git config --global user.email "jigar.dafda@gmail.com"
        git config --global user.name "Jigar Dafda"

        git clone https://$(GITHUB_USERNAME):$(GITHUB_PERSONAL_TOKEN)@github.com/gofynd/fdk-store.git
        cd fdk-store
        git checkout -b $BRANCH_NAME
        rm -rf ./*
        cd ..

        cp -R `ls | grep -v "fdk-store"` ./fdk-store
        cp .gitignore.ci ./fdk-store/.gitignore

        cd fdk-store
        NODE_ENV=development npm i
        npm run build
        npm run doc

        git add .
        git commit -m "[Auto Generated]"
        git push origin $BRANCH_NAME

        git tag $TAG_NAME
        git push origin $TAG_NAME

        # Push to master branch
        git checkout master
        git pull origin master
        git merge $BRANCH_NAME
        git push origin master
      else
        echo "This is not a v2 tag push. Exiting..."
        exit 0
      fi
    displayName: 'Sync with GitHub'
