trigger:
  tags:
    include:
      - "v*"

resources:
  containers:
    - container: node18
      image: node:18-buster

pool:
  docker

variables:
- group: pipeline

jobs:
- job: GitHubSync
  container: node18
  steps:
  - checkout: self

  - script: |
      if [ "$(Build.SourceBranch)" != "refs/tags/*" ]; then

        echo "This is a tag push. Sync starting..."
        BRANCH_NAME=$(echo $(Build.SourceBranchName) | sed 's/^refs\/tags\///' | sed 's/\./_/g')

        git config --global user.email "jigar.dafda@gmail.com"
        git config --global user.name "Jigar Dafda"

        git clone https://$(GITHUB_USERNAME):$(GITHUB_PERSONAL_TOKEN)@github.com/gofynd/fdk-store.git
        cd fdk-store
        git checkout -b $BRANCH_NAME
        rm -rf ./*
        cd ..

        cp -R `ls | grep -v "fdk-store"` ./fdk-store
        cp .gitignore.ci ./fdk-store/.gitignore

        cd fdk-store
        NODE_ENV=development npm i
        npm run build
        npm run doc

        git add .
        git commit -m "[Auto Generated]"
        git push origin $BRANCH_NAME

        git tag $(Build.SourceBranchName)
        git push origin $(Build.SourceBranchName)

      else
        echo "$(Build.SourceBranch)"
        echo "This is not a tag push. Exiting..."
        exit 0
      fi
    displayName: 'Sync with GitHub'
