import { AnnouncementsResponseSchema, ApplicationLegal, BlogGetResponse, BlogSchema, DataLoadersSchema, GetFaqSchema, LandingPageSchema, NavigationGetResponse, PageSchema, SeoComponent, SlideshowGetResponse, Support, TagsSchema } from "fdk-client-javascript/sdk/application/Content/ContentApplicationModel";
import { CommonAsyncLoadingTypes } from ".";
export type NavigationType = Partial<NavigationGetResponse & CommonAsyncLoadingTypes>;
export type SEO = Partial<SeoComponent & CommonAsyncLoadingTypes>;
export type Blog = Partial<BlogSchema & CommonAsyncLoadingTypes>;
export type Blogs = Partial<BlogGetResponse & CommonAsyncLoadingTypes>;
export type CustomPage = Partial<PageSchema & CommonAsyncLoadingTypes>;
export type FAQData = Partial<GetFaqSchema & CommonAsyncLoadingTypes>;
export type Tags = Partial<TagsSchema & CommonAsyncLoadingTypes>;
export type LegalData = Partial<ApplicationLegal & CommonAsyncLoadingTypes>;
export type ScreenSaver = Partial<SlideshowGetResponse & CommonAsyncLoadingTypes>;
export type SupportInformation = Partial<Support & CommonAsyncLoadingTypes>;
export type Announcement = Partial<AnnouncementsResponseSchema & CommonAsyncLoadingTypes>;
export type LandingPage = Partial<LandingPageSchema & CommonAsyncLoadingTypes>;
export type DataLoaders = Partial<DataLoadersSchema & CommonAsyncLoadingTypes>;
export type ContentSlice = {
    navigation: NavigationType;
    seo: SEO;
    blog: Blog;
    blogs: Blogs;
    custom_page: CustomPage;
    faq_data: FAQData;
    tags: Tags;
    legal_data: LegalData;
    screen_saver: ScreenSaver;
    support_information: SupportInformation;
    announcement: Announcement;
    landing_page: LandingPage;
    data_loaders: DataLoaders;
};
