import { BulkPriceResponse } from "fdk-client-javascript/sdk/application/Cart/CartApplicationModel";
import type { ProductCompareResponse, ProductDetail, ProductFrequentlyComparedSimilarResponse, ProductSizePriceResponseV3, ProductSizes, ProductSizeSellersResponseV3, ProductVariantsResponse } from "fdk-client-javascript/sdk/application/Catalog/CatalogApplicationModel";
import { CommonAsyncLoadingTypes } from ".";
export type ProductDetails = Partial<ProductDetail & CommonAsyncLoadingTypes>;
export type ProductVariants = Partial<ProductVariantsResponse & CommonAsyncLoadingTypes>;
export type ProductMeta = Partial<ProductSizes & CommonAsyncLoadingTypes>;
export type BulkPrice = Partial<BulkPriceResponse & CommonAsyncLoadingTypes>;
export type SimilarCompareProducts = Partial<ProductCompareResponse & CommonAsyncLoadingTypes>;
export type FrequentlyComparedProducts = Partial<ProductFrequentlyComparedSimilarResponse & CommonAsyncLoadingTypes>;
export type ProductPriceBySlug = Partial<ProductSizePriceResponseV3 & CommonAsyncLoadingTypes>;
export type ProductSellerBySlug = Partial<ProductSizeSellersResponseV3 & CommonAsyncLoadingTypes>;
export type ProductSlice = {
    product_details: ProductDetails;
    product_variants: ProductVariants;
    product_meta: ProductMeta;
    bulk_price: BulkPrice;
    similar_compare_products: SimilarCompareProducts;
    frequently_compared_products: FrequentlyComparedProducts;
    product_price_by_slug: ProductPriceBySlug;
    product_seller_by_slug: ProductSellerBySlug;
};
