import { BulkPriceResponse } from "@gofynd/fdk-client-javascript/sdk/application/Cart/CartApplicationModel";
import type { ApplicationStoreListing, FollowerCountResponse, FollowIdsResponse, FollowPostResponse, GetFollowListingResponse, ProductCompareResponse, ProductDetail, ProductFrequentlyComparedSimilarResponse, ProductSizePriceResponseV3, ProductSizes, ProductSizeSellersResponseV3, ProductVariantsResponse, StoreDetails, StoreListingResponse } from "@gofynd/fdk-client-javascript/sdk/application/Catalog/CatalogApplicationModel";
import { CommonAsyncLoadingTypes } from ".";
export type ProductDetails = Partial<ProductDetail & CommonAsyncLoadingTypes>;
export type ProductVariants = Partial<ProductVariantsResponse & CommonAsyncLoadingTypes>;
export type ProductMeta = Partial<ProductSizes & CommonAsyncLoadingTypes>;
export type BulkPrice = Partial<BulkPriceResponse & CommonAsyncLoadingTypes>;
export type SimilarCompareProducts = Partial<ProductCompareResponse & CommonAsyncLoadingTypes>;
export type FrequentlyComparedProducts = Partial<ProductFrequentlyComparedSimilarResponse & CommonAsyncLoadingTypes>;
export type ProductPriceBySlug = Partial<ProductSizePriceResponseV3 & CommonAsyncLoadingTypes>;
export type ProductSellerBySlug = Partial<ProductSizeSellersResponseV3 & CommonAsyncLoadingTypes>;
export type FollowByIdParamSlug = Partial<FollowPostResponse & CommonAsyncLoadingTypes>;
export type FollowerCountByIdSlug = Partial<FollowerCountResponse & CommonAsyncLoadingTypes>;
export type FollowedList = Partial<GetFollowListingResponse & CommonAsyncLoadingTypes>;
export type FollowIdsResponseSlug = Partial<FollowIdsResponse & CommonAsyncLoadingTypes>;
export type StoresDetails = Partial<StoreListingResponse & CommonAsyncLoadingTypes>;
export type InStockLocations = Partial<ApplicationStoreListing & CommonAsyncLoadingTypes>;
export type LocationDetailsById = Partial<StoreDetails & CommonAsyncLoadingTypes>;
export type ProductSlice = {
    product_details: ProductDetails;
    product_variants: ProductVariants;
    product_meta: ProductMeta;
    bulk_price: BulkPrice;
    similar_compare_products: SimilarCompareProducts;
    frequently_compared_products: FrequentlyComparedProducts;
    product_price_by_slug: ProductPriceBySlug;
    product_seller_by_slug: ProductSellerBySlug;
    follow_by_id: FollowByIdParamSlug;
    follower_count_by_id: FollowerCountByIdSlug;
    followed_listing: FollowedList;
    fetch_follow_ids: FollowIdsResponseSlug;
    unfollow_by_id: FollowByIdParamSlug;
    stores_details: StoresDetails;
    instock_locations: InStockLocations;
    location_details: LocationDetailsById;
};
