import type ApplicationClient from "@gofynd/fdk-client-javascript/sdk/application/ApplicationClient";
import { ToolkitStore } from "@reduxjs/toolkit/dist/configureStore";
import { CatalogModule } from "./modules/catalog";
import { CartModule } from "./modules/cart";
import { BrandsModule } from "./modules/brands";
import { CategoriesModule } from "./modules/categories";
import { AuthModule } from "./modules/auth";
import { PaymentModule } from "./modules/payment";
import { AddressModule } from "./modules/address";
import { ContentModule } from "./modules/content";
import { ThemeModule } from "./modules/theme";
import { ConfigurationModule } from "./modules/configuration";
import { LogisticModule } from "./modules/logistic";
import { ShareModule } from "./modules/share";
import { CollectionModule } from "./modules/collection";
import { OrderModule } from "./modules/order";
import { CustomModule } from "./modules/custom";
import { EventEmitterFunction } from "../types";
import { fileStorageModule } from "./modules/fileStorage";
import { LeadModule } from "./modules/lead";
declare class ApplicationStore {
    store: ToolkitStore;
    getters: any;
    catalog: CatalogModule;
    cart: CartModule;
    brands: BrandsModule;
    address: AddressModule;
    content: ContentModule;
    theme: ThemeModule;
    configuration: ConfigurationModule;
    logistic: LogisticModule;
    payment: PaymentModule;
    auth: AuthModule;
    share: ShareModule;
    collection: CollectionModule;
    categories: CategoriesModule;
    order: OrderModule;
    fileStorage: fileStorageModule;
    custom: CustomModule;
    lead: LeadModule;
    constructor(sdk: ApplicationClient, initialData: any, eventEmitter?: EventEmitterFunction);
    observeStore(selector: Function, onChange: Function): import("redux").Unsubscribe;
}
export default ApplicationStore;
